name: PR Labeler

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 全履歴を取得する

      - name: Extract commit messages
        run: |
          COMMITS=$(git log --format=%B)
          echo "$COMMITS"
          echo "$COMMITS" > commits.txt
      
      - name: Debug - Print commits
        run: cat commits.txt
      
      - name: Set labels based on commit messages
        id: set-labels
        run: |
          labels=()
          while IFS= read -r commit; do
            echo "Processing commit: $commit"  # デバッグ用出力
            if [[ $commit =~ ^feat ]]; then
              labels+=("feature")
            elif [[ $commit =~ ^fix ]]; then
              labels+=("bug")
            elif [[ $commit =~ ^docs ]]; then
              labels+=("documentation")
            elif [[ $commit =~ ^style ]]; then
              labels+=("style")
            elif [[ $commit =~ ^refactor ]]; then
              labels+=("refactor")
            elif [[ $commit =~ ^test ]]; then
              labels+=("test")
            elif [[ $commit =~ ^chore ]]; then
              labels+=("chore")
            fi
          done < commits.txt
          
          # Remove duplicate labels
          unique_labels=($(echo "${labels[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))
          
          # Debug output for unique labels
          echo "Unique labels: ${unique_labels[*]}"

          # Set the output
          echo "labels=${unique_labels[*]}" >> $GITHUB_OUTPUT

      - name: Add labels to PR
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: ${{ steps.set-labels.outputs.labels }}
